function handles=gui()
%% Crea la figura principal de la interfaz gráfica
% Devuelve: Objeto handles (1x1 struct) con las variables de tipo handle a los controles UI 

    %% Main Window
    
    handles.d=figure('Name','Caracterización de recintos por IR');
    handles.d.NumberTitle='off';
    handles.d.Units='pixel';
    handles.d.OuterPosition=[50 50 800 700];
    handles.d.Resize='on';
    handles.d.MenuBar = 'none';
    movegui(handles.d,'center');
    handles.d.Visible = 'on';
       
    %% Pestañas
    
    handles.tabgrp = uitabgroup(handles.d,'OuterPosition',[.005 .005 .995 .995]);
        handles.tabMedicion = uitab(handles.tabgrp,'Title','Medición');
        handles.tabCalculos = uitab(handles.tabgrp,'Title','Calculos');
    
    handles.tabgrptablas = uitabgroup(handles.tabCalculos,'OuterPosition',[.005 .005 .995 .25]);
        handles.tabOctavas = uitab(handles.tabgrptablas,'Title','Octavas');
        handles.tabTercios = uitab(handles.tabgrptablas,'Title','Tercios');
    
    %% Autores
    %
%     uicontrol('Parent',handles.d,'Style','text','units','normalized',...
%         'Position', [0.4 0.97 0.7 0.02],...
%         'String','Alumnos: Almaraz Juan, Montemarano Marcos, Gonzalez Ian',...
%         'Fontname', 'calibri','Fontsize',10);
%% Panels
    %Panel Ajuste
    handles.pnlAjuste = uipanel('Parent',handles.tabMedicion,...
        'Title','Ajuste (Ruido Rosa)',...
        'units','normalized',...
        'Position',[0.02 0.76 0.4 0.15],...
        'Fontname','arial','Fontsize',10);
    %Panel Parametros 
    handles.pnlParametros = uipanel('Parent',handles.tabMedicion,...
        'Title','1. Ingresar parámetros',...
        'units','normalized',...
        'Position', [0.02 0.4 0.48 0.3],...
        'Fontname', 'arial','Fontsize',11);
    
        handles.panelGenerarSS = uipanel('Parent',handles.tabMedicion,...
        'Title','2. Generar archivos .wav',...
        'units','normalized',...
        'Position',[0.02 0.05 0.48 0.3],...
        'Fontname','arial','Fontsize',11);
    
    handles.panelGrabar = uipanel('Parent',handles.tabMedicion,...
        'Title','3a. Adquisición',...
        'units','normalized',...
        'Position',[0.50 0.4 0.48 0.3],...
        'Fontname','arial','Fontsize',11);
    
    handles.panelConvol = uipanel('Parent',handles.tabMedicion,...
        'Title','3b. Cargar Grabaciones',...
        'units','normalized',...
        'Position',[0.50 0.05 0.48 0.3],...
        'Fontname','arial','Fontsize',11);        
    handles.panelCalculos = uipanel('Parent',handles.tabCalculos,...
        'Title','Cargar Ir´s y Calcular',...
        'units','normalized',...
        'Position', [0.005 0.3 0.25 0.68],...
        'Fontname', 'arial','Fontsize',10);
 %% Imagen de GUI  
    handles.pnlImagen = uipanel('Parent',handles.tabMedicion,'units','Normalized','Position',[0.43, 0.76, 0.55 0.2]);
    handles.imgaxx = axes(handles.pnlImagen,'units','normalized','Position',[0, 0, 1, 1]);
    [img,~] = imread('Image\LogoPractica.png');image(handles.imgaxx,img); axis off;
    
%% 1. Ajuste con Ruido Rosa / Boton y label
   %Boton play
    handles.btnPlayRR = uicontrol('Parent',handles.pnlAjuste,...
        'Style','pushbutton',...
        'units','normalized',...
        'Position',[0.05 0.2 0.45 0.65],...
        'String','Reproducir');
    %Boton stop
    handles.btnStopRR = uicontrol('Parent',handles.pnlAjuste,...
        'Style','pushbutton',...
        'units','normalized',...
        'Position',[0.50 0.2 0.45 0.65],...
        'String','Detener');

%% 2. Panel Grabar archivos de audio .wav/botones y labels
    % FRECUENCIA INICIAL
    %Label
    uicontrol('Parent',handles.pnlParametros,...
        'Style','text',...
        'units','normalized',...
        'Position',[0.02 0.72 0.6 0.2],...
        'HorizontalAlignment','left',...
        'String','Frecuencia inicial [Hz]','Fontsize',9);
    %TextBox
    handles.txtf1 = uicontrol('Parent',handles.pnlParametros,...
        'Style','edit',...
        'units','normalized',...
        'Position',[0.72 0.72 0.2 0.2],...
        'String','20');

    % FRECUENCIA FINAL
    %Label
    uicontrol('Parent',handles.pnlParametros,...
        'Style','text',...
        'units','normalized',...
        'Position',[0.02 0.52 0.6 0.2],...
        'HorizontalAlignment','left',...
        'String','Frecuencia final [Hz]','Fontsize',9);
    %TextBox
    handles.txtf2 = uicontrol('Parent',handles.pnlParametros,...
        'Style','edit',...
        'units','normalized',...
        'Position',[0.72 0.52 0.2 0.2],...
        'String','8000');

    % FRECUENCIA SALMPLEO
    %Label
    uicontrol('Parent',handles.pnlParametros,...
        'Style','text',...
        'units','normalized',...
        'Position',[0.02 0.32 0.75 0.2],...
        'HorizontalAlignment','left',...
        'String','Frecuencia de muestreo [Hz]','Fontsize',9);
    %TextBox
    handles.txtfm = uicontrol('Parent',handles.pnlParametros,...
        'Style','edit',...
        'units','normalized',...
        'Position',[0.72 0.32 0.2 0.2],...
        'String','44100');

    % DURACION T[s]
    %Label
    uicontrol('Parent',handles.pnlParametros,...
        'Style','text',...
        'units','normalized',...
        'Position',[0.02 0.12 0.6 0.2],...
        'HorizontalAlignment','left',...
        'String','Duración [s]','Fontsize',9);
    %Textbox
    handles.txtT = uicontrol('Parent',handles.pnlParametros,...
        'Style','edit',...
        'units','normalized',...
        'Position',[0.72 0.12 0.2 0.2],...
        'String','10');
    
    % Panel Sine Sweep /Botones
    handles.btnGrabarSS = uicontrol('Parent',handles.panelGenerarSS,...
        'Style','pushbutton',...
        'units','normalized',...
        'Position',[0.05 0.65 0.9 0.3],...
        'String','Grabar archivos SineSweep.wav & ISS.wav');

    handles.btnRepSS = uicontrol('Parent',handles.panelGenerarSS,...
        'Style','pushbutton',...
        'units','normalized',...
        'Position',[0.05 0.35 0.45 0.3],...
        'String','Reproducir Sine Sweep');

    handles.btnRepISS = uicontrol('Parent',handles.panelGenerarSS,...
        'Style','pushbutton',...
        'units','normalized',...
        'Position',[0.5 0.35 0.45 0.3],...
        'String','Reproducir ISS');

    handles.btnStopSS = uicontrol('Parent',handles.panelGenerarSS,...
        'Style','pushbutton',...
        'units','normalized',...
        'Position',[0.05 0.05 0.9 0.3],...
        'String','Detener');

%% 3a. Panel Adquisición/Botones, labels
    uicontrol('Parent',handles.panelGrabar,...
        'Style','text',...
        'units','normalized',...
        'Position',[0.05 0.4 0.8 0.5],...
        'HorizontalAlignment','left',...
        'String','Reproducir Sine Sweep generado y grabar en simultáneo',...
        'Fontsize',9);
    handles.btnAdquirir = uicontrol('Parent',handles.panelGrabar,...
        'Style','pushbutton',...
        'units','normalized',...
        'Position',[0.05 0.25 0.9 0.3],...
        'String','Grabar y Generar IR');
    

%% 3b. Grabaciones preexistentes /label, button
    uicontrol('Parent',handles.panelConvol,...
        'Style','text',...
        'units','normalized',...
        'Position',[0.05 0.4 0.8 0.5],...
        'HorizontalAlignment','left',...
        'String','Generar IR a partir de una grabación preexistente',...
        'Fontsize',9);
    
    handles.btnCargarGrab = uicontrol('Parent',handles.panelConvol,...
        'Style','pushbutton',...
        'units','normalized',...
        'Position',[0.05 0.25 0.9 0.3],...
        'String','Cargar Grabaciones y Generar IR´s..');


%% Calculos
    %% Ejes
    handles.axx=axes(handles.tabCalculos,'units','normalized',...
        'Position',[0.32 0.34 0.66 0.62]);
        axis(handles.axx,[0 2 -100 5]);
        xlabel('Tiempo[s]');ylabel('dB');
    %% Tabla
    handles.tablaoctava=uitable('Parent',handles.tabOctavas,'Visible','on','units','normalized',...
        'Position',[0 0 1 1]);
    handles.tablaoctava.RowName={'TR10','TR20','TR30','EDT'};
    handles.tablaoctava.ColumnName={'     31,5 Hz     ','     63 Hz     ','     125 Hz     ','     250 Hz     ','     500 Hz     ','     1000 Hz     ','     2000 Hz     ','     4000 Hz     ','     8000 Hz     ','     16000 Hz     '};
   
    handles.tablatercio=uitable('Parent',handles.tabTercios,'Visible','on','units','normalized',...
        'Position',[0 0 1 1]);
    handles.tablatercio.RowName={'TR10','TR20','TR30','EDT'};
    handles.tablatercio.ColumnName={'     25 Hz     ','     31,5 Hz     ','     40 Hz     ','     50 Hz     ','     63 Hz     ','    80 Hz     ','     100 Hz     ', '     125 Hz     ', '     160 Hz     ', '     200 Hz     ', '     250 Hz     ', '     315 Hz     ', '     400 Hz     ', '     500 Hz     ', '     630 Hz     ', '     800 Hz     ', '     1000 Hz     ', '     1250 Hz     ', '     1600 Hz     ', '     2000 Hz     ', '     2500 Hz     ', '     3150 Hz     ', '     4000 Hz     ', '     5000 Hz     ', '     6300 Hz     ', '     8000 Hz     ', '     10000 Hz     ', '     12500 Hz     ', '     16000 Hz     ', '     20000 Hz     '};
    %% Botones
    % Seleccionar archivo
    handles.seleccionararchivo = uicontrol('Parent',handles.panelCalculos,... 
        'Style','pushbutton',...
        'units','normalized',...
        'Position',[0.05 0.85 0.9 0.10],...
        'String','Cargar impulso(s)...',...
        'FontSize',10,...
        'Enable','on');
    % Boton Calcular
    handles.calcular = uicontrol('Parent',handles.panelCalculos,... 
        'Style','pushbutton',...
        'units','normalized',...
        'Position',[0.05 0.75 0.9 0.10],...
        'String','Calcular',...
        'FontSize',10,...
        'Enable','off');
    % Boton Graficar
    handles.graficar = uicontrol('Parent',handles.panelCalculos,... 
        'Style','pushbutton',...
        'units','normalized',...
        'Position',[0.05 0.05 0.9 0.10],...
        'String','Graficar',...
        'FontSize',10,...
        'Enable','off');
    
    
    %% Selector de IR 
    uicontrol('Parent',handles.panelCalculos,...
        'Style','text',...
        'units','normalized',...
        'Position',[0.05 0.6 0.9 0.1],...
        'HorizontalAlignment','left',...
        'String','Respuesta a graficar:','Fontsize',9);  
    
    handles.selectorIR = uicontrol('Parent',handles.panelCalculos,...
        'Style','popupmenu',...
        'units','normalized',...
        'Position',[0.05 0.55 0.9 0.1],...
        'Value',1,...
        'String',{'Cargue IR(s)..'},...
        'FontSize',8);  
    
    %% Selector Octava o Tercios
    handles.selectorOctavaTercios = uibuttongroup('Parent',handles.panelCalculos, 'Title', 'Seleccionar filtro', ...
        'Position', [0.05 0.32 0.9 0.23]);
    handles.optionOctavas = uicontrol(handles.selectorOctavaTercios, 'Style', 'radiobutton', 'String', 'Octava', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.6 0.9 0.2 ]);
    handles.optionTercios = uicontrol(handles.selectorOctavaTercios, 'Style', 'radiobutton', 'String', 'Tercio de octava', ...
        'Units', 'normalized', ...
        'Position', [0.05 0.2 0.9 0.2]);
    
    %% Selector de banda a plotear
    uicontrol('Parent',handles.panelCalculos,...
        'Style','text',...
        'units','normalized',...
        'Position',[0.05 0.2 0.9 0.10],...
        'HorizontalAlignment','left',...
        'String','Frecuencia a graficar:','Fontsize',9);  
    handles.selectorFiltro = uicontrol('Parent',handles.panelCalculos,...
        'Style','popupmenu',...
        'units','normalized',...
        'Enable','off',...
        'Position',[0.05 0.15 0.9 0.1],...
        'Value',3,...
        'String',{'31,5 Hz','63 Hz','125 Hz','250 Hz','500 Hz','1000 Hz','2000 Hz','4000 Hz','8000 Hz','16000 Hz'},...
        'FontSize',8);  
end